### ISSUE TITLE
Bugs i have found in 0.1.1 :)

### ISSUE THREAD

**Issue by Switch0r** [kitskub/MyHungerGames#1]
- Player freeze does not work anymore.
- Still does not save to the config yml. (only when shutting down the server its saves)
- Internal error spams the server when a player leaves the arena with /hg leave or when he leaves the server when he is in the game.

2012-04-26 19:50:25 [INFO] Switch0r lost connection: disconnect.quitting
2012-04-26 19:50:25 [SEVERE] Could not pass event PlayerQuitEvent to HungerGames
java.lang.IllegalArgumentException: Cannot drop a Null item.
    at org.apache.commons.lang.Validate.notNull(Validate.java:203)
    at org.bukkit.craftbukkit.CraftWorld.dropItem(CraftWorld.java:528)
    at org.bukkit.craftbukkit.CraftWorld.dropItemNaturally(CraftWorld.java:547)
    at com.randude14.hungergames.games.HungerGame.dropInventory(HungerGame.java:552)
    at com.randude14.hungergames.games.HungerGame.leave(HungerGame.java:320)
    at com.randude14.hungergames.GameManager.playerLeft(GameManager.java:134)
    at com.randude14.hungergames.GameManager.playerQuit(GameManager.java:121)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:461)
    at net.minecraft.server.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:179)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:698)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:234)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:92)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:622)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:506)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

2012-04-26 19:49:32 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'hga' in plugin HungerGames v0.1.0
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:636)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:821)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:781)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:92)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:622)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:506)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NullPointerException
    at com.randude14.hungergames.Commands.handleAdminCommand(Commands.java:435)
    at com.randude14.hungergames.Commands.onCommand(Commands.java:26)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 12 more

**Comment by kitskub** [comment]
In the latest builds, as of now, the only thing that shouldn't be fixed is the config saving. And on that, it might be fixed, but I don't know yet.
