### ISSUE TITLE
Vote issue

### ISSUE THREAD

**Issue by illumi241** [kitskub/MyHungerGames#16]
If I type /hg vote in the chat it is for every game not only the current game (all following games too), would be nice if this could be fixed.

**Comment by kitskub** [comment]
Players can only be in one game at a time. So, voting is only counted for the game your in.

**Comment by illumi241** [comment]
I meant if I voted for a game to play, than after the game has finished and I want to join the game again, it sais I have already voted but I've not. If i'm not ready to play I can't say that I'm ready because the vote allready is there.
I used the dev build, maybe there is a but in it?

**Comment by kitskub** [comment]
I'll take a look. Reopening until I check

**Comment by kitskub** [comment]
I don't see how this could  be an issue. Possibly there is an error in the console?

**Comment by illumi241** [comment]
Hmm I'll test it today again and than I'll send you the whole log from the join to gamestart, but the last time it only said 'You've already casted your vote that you are ready to play'
'You have voted that you are ready'
and the game doesn't start.

**Comment by illumi241** [comment]
Nope there is no Information about it in the Server Log.
There are two Errors later, when I tried to spectate, there was an internal Server error (but isn't related to vote issue):
2012-07-28 16:09:27 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'hg' in plugin MyHungerGames v0.6-dev
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:651)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:822)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:782)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:765)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:114)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:97)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:640)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:518)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
    at com.randude14.hungergames.commands.user.SpectateCommand.handle(SpectateCommand.java:43)
    at com.randude14.hungergames.commands.SubCommand.execute(SubCommand.java:33)
    at com.randude14.hungergames.commands.CommandHandler.handleUserCommand(CommandHandler.java:82)
    at com.randude14.hungergames.commands.CommandHandler.onCommand(CommandHandler.java:30)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 12 more

**Comment by kitskub** [comment]
Well, the spectate error has been fixed in the latest builds. Let's wait until the next version to see if this is still there.

**Comment by kitskub** [comment]
I fixed this
