### ISSUE TITLE
Unhandled exception executing command 'hga' in plugin MyHungerGames v0.6

### ISSUE THREAD

**Issue by WoAnerges** [kitskub/MyHungerGames#19]
When I try to create a new game with "/hga add game My Hunger Game"

18:31:12 [SEVERE] null
org.bukkit.command.CommandException Unhandled exception executing command 'hga' in plugin MyHungerGames v0.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:492)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:878)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:825)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:807)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:276)
        at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
        at net.minecraft.server.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:581)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
        at com.randude14.hungergames.HungerGames.parseToString(HungerGames.java:319)
        at com.randude14.hungergames.games.HungerGame.saveTo(HungerGame.java:220)
        at com.randude14.hungergames.GameManager.saveGame(GameManager.java:170)
        at com.randude14.hungergames.GameManager.saveGames(GameManager.java:147)
        at com.randude14.hungergames.GameManager.createGame(GameManager.java:40)
        at com.randude14.hungergames.commands.admin.add.AddGameCommand.handle(AddGameCommand.java:34)
        at com.randude14.hungergames.commands.SubCommand.execute(SubCommand.java:33)
        at com.randude14.hungergames.commands.CommandHandler.handleAdminCommand(CommandHandler.java:194)
        at com.randude14.hungergames.commands.CommandHandler.onCommand(CommandHandler.java:32)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        ... 15 more

**Comment by WoAnerges** [comment]
Possibly fixed with a new beta update. Confirmed, that error does not appear with the latest build anymore.
