### ISSUE TITLE
Errors in 0.1.2.

### ISSUE THREAD

**Issue by Switch0r** [kitskub/MyHungerGames#2]
/hg join gives this error:

2012-04-27 16:23:55 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'hg' in plugin HungerGames v0.1.2
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:636)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:821)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:781)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:92)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:622)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:506)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NullPointerException
    at com.randude14.hungergames.Commands.handleUserCommand(Commands.java:79)
    at com.randude14.hungergames.Commands.onCommand(Commands.java:25)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 12 more

/hg leave gives this error:

2012-04-27 16:27:47 [INFO] Remaining players: CraftPlayer{name=Switch0r}, CraftPlayer{name=MiNiMaLHaDeZz}
2012-04-27 16:27:47 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'hg' in plugin HungerGames v0.1.2
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:636)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:821)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:781)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:92)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:622)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:506)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NullPointerException
    at com.randude14.hungergames.Commands.handleUserCommand(Commands.java:96)
    at com.randude14.hungergames.Commands.onCommand(Commands.java:25)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 12 more

**Comment by kitskub** [comment]
Thank you. I will fix this when I get home.
