### ISSUE TITLE
[SEVERE] Could not pass event PlayerLeaveGameEvent to MyHungerGames

### ISSUE THREAD

**Issue by WoAnerges** [kitskub/MyHungerGames#20]
16:17:54 [SEVERE] Could not pass event PlayerLeaveGameEvent to MyHungerGames
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:332)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at com.randude14.hungergames.HungerGames.callEvent(HungerGames.java:314)
        at com.randude14.hungergames.games.HungerGame.leave(HungerGame.java:807)
        at com.randude14.hungergames.GameManager.playerLeftServer(GameManager.java:125)
        at com.randude14.hungergames.listeners.PlayerListener.playerQuit(PlayerListener.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:330)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at net.minecraft.server.ServerConfigurationManagerAbstract.disconnect(ServerConfigurationManagerAbstract.java:206)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:711)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:281)
        at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
        at net.minecraft.server.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:581)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
        at com.randude14.hungergames.stats.TimeListener.playerStopped(TimeListener.java:76)
        at com.randude14.hungergames.stats.TimeListener.onPlayerLeave(TimeListener.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:330)
        ... 28 more

16:20:17 [INFO] [MyHungerGames] 0.6 - Player1 killed Player2 in game Hunger. 16:20:17 [INFO] [MyHungerGames] 0.6 - Player1 has won the game Hunger! Congratulations! 16:20:17 [SEVERE] [Fatal Error] :1:1: Premature end of file.

16:20:17 [SEVERE] [Fatal Error] :1:1: Premature end of file.

16:20:17 [SEVERE] [Fatal Error] :1:1: Premature end of file.

**Comment by WoAnerges** [comment]
Possibly fixed with a new beta update. Confirmed, that error does not appear with the latest build anymore.
