### ISSUE TITLE
When Spectator| Error

### ISSUE THREAD

**Issue by WoAnerges** [kitskub/MyHungerGames#23]
After using /hg spectate
and then trying /hg leave,
this error appears and you cannot leave a game.

16:25:02 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'hg' in plugin MyHungerGames v0.7-dev
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:492)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:880)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:826)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:808)
        at net.minecraftserverhook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:124)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:276)
        at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
        at net.minecraftserverhook.NetServerHandlerProxy.d(NetServerHandlerProxy.java:58)
        at net.minecraft.server.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:578)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:366)
        at org.bukkit.craftbukkit.entity.CraftEntity.teleport(CraftEntity.java:162)
        at com.randude14.hungergames.games.HungerGame.removeSpectator(HungerGame.java:330)
        at com.randude14.hungergames.commands.user.SpectateCommand.handle(SpectateCommand.java:28)
        at com.randude14.hungergames.commands.SubCommand.execute(SubCommand.java:34)
        at com.randude14.hungergames.commands.CommandHandler.handleUserCommand(CommandHandler.java:88)
        at com.randude14.hungergames.commands.CommandHandler.onCommand(CommandHandler.java:30)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        ... 17 more
16:25:02 [INFO] [MyHungerGames] 0.7-dev - 2 minute(s), 15 second(s)...

**Comment by WoAnerges** [comment]
MyHungerGames Build#28

**Comment by kitskub** [comment]
Did you get an error when you started spectating?

**Comment by WoAnerges** [comment]
This error appears, when trying /hg leave, after successfully started spectating.

btw, when spectating, it is not following a player.

**Comment by kitskub** [comment]
I believe I have fixed this
