### ISSUE TITLE
When Quit| Error

### ISSUE THREAD

**Issue by WoAnerges** [kitskub/MyHungerGames#26]
11:05:21 [INFO] player[/12.34.56.78:55610] logged in with entity id 2544679 at ([World1] 326.5, 74.0, 618.5)
11:05:21 [INFO] Disconnecting player[/12.34.56.78:55610]: Internal server error
11:05:21 [WARNING] Failed to handle packet: java.lang.IllegalStateException: Failed to add player. EntityPlayer['player'/2544679, l='Tournament', x=156.07, y=72.00, z=233.86](player at 156.0669973735024,72.0,233.85747086099627) already is in chunk -1, 4
java.lang.IllegalStateException: Failed to add player. EntityPlayer['player'/2544679, l='Tournament', x=156.07, y=72.00, z=233.86](player at 156.0669973735024,72.0,233.85747086099627) already is in chunk -1, 4
        at net.minecraft.server.PlayerInstance.a(PlayerInstance.java:28)
        at net.minecraft.server.PlayerManager.addPlayer(PlayerManager.java:101)
        at net.minecraft.server.ServerConfigurationManagerAbstract.a(ServerConfigurationManagerAbstract.java:123)
        at net.minecraft.server.ServerConfigurationManagerAbstract.c(ServerConfigurationManagerAbstract.java:172)
        at net.minecraft.server.ServerConfigurationManagerAbstract.a(ServerConfigurationManagerAbstract.java:92)
        at net.minecraft.server.NetLoginHandler.d(NetLoginHandler.java:121)
        at net.minecraft.server.NetLoginHandler.c(NetLoginHandler.java:41)
        at net.minecraft.server.DedicatedServerConnectionThread.a(DedicatedServerConnectionThread.java:44)
        at net.minecraft.server.DedicatedServerConnection.b(SourceFile:29)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:578)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
11:05:23 [INFO] player lost connection: disconnect.endOfStream

**Comment by kitskub** [comment]
This does not look like a MyHungerGames error.

**Comment by WoAnerges** [comment]
Just to let you know about such thing.
