### ISSUE TITLE
Errors, when do /hg join Tournament

### ISSUE THREAD

**Issue by WoAnerges** [kitskub/MyHungerGames#29]
13:36:42 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'hg' in plugin MyHungerGames v0.7-dev
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:492)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:880)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:826)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:808)
        at net.minecraftserverhook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:124)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:276)
        at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
        at net.minecraftserverhook.NetServerHandlerProxy.d(NetServerHandlerProxy.java:58)
        at net.minecraft.server.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:578)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:366)
        at org.bukkit.craftbukkit.entity.CraftEntity.teleport(CraftEntity.java:162)
        at com.randude14.hungergames.games.HungerGame.removeSpectator(HungerGame.java:330)
        at com.randude14.hungergames.commands.user.SpectateCommand.handle(SpectateCommand.java:28)
        at com.randude14.hungergames.commands.SubCommand.execute(SubCommand.java:34)
        at com.randude14.hungergames.commands.CommandHandler.handleUserCommand(CommandHandler.java:88)
        at com.randude14.hungergames.commands.CommandHandler.onCommand(CommandHandler.java:30)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        ... 17 more
13:36:50 [WARNING] [MyHungerGames] Task #96918 for MyHungerGames v0.7-dev generated an exception
java.lang.IllegalArgumentException: n must be positive
        at java.util.Random.nextInt(Random.java:265)
        at com.randude14.hungergames.games.HungerGame.run(HungerGame.java:247)
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:52)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:316)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:510)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

**Comment by kitskub** [comment]
I think this has been fixed in the latest builds

**Comment by WoAnerges** [comment]
This error happens on 0.7-dev-082620122041
