### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by Mozzi3** [kitskub/MyHungerGames#33]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
    at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:114)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:547)
    at net.minecraft.server.Packet14BlockDig.handle(SourceFile:46)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:577)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at com.randude14.hungergames.Plugin.getSpectating(Plugin.java:448)
    at com.randude14.hungergames.listeners.BlockListener.onPlayerInteract(BlockListener.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 16 more
2012-10-10 17:30:28 [SEVERE] Could not pass event PlayerInteractEvent to HungerGames
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
    at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:114)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:547)
    at net.minecraft.server.Packet14BlockDig.handle(SourceFile:46)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:577)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at com.randude14.hungergames.Plugin.getSpectating(Plugin.java:448)
    at com.randude14.hungergames.listeners.BlockListener.onPlayerInteract(BlockListener.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 16 more
2012-10-10 17:30:28 [SEVERE] Could not pass event PlayerInteractEvent to HungerGames
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
    at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:114)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:547)
    at net.minecraft.server.Packet14BlockDig.handle(SourceFile:46)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:577)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at com.randude14.hungergames.Plugin.getSpectating(Plugin.java:448)
    at com.randude14.hungergames.listeners.BlockListener.onPlayerInteract(BlockListener.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 16 more
2012-10-10 17:30:28 [SEVERE] Could not pass event PlayerInteractEvent to HungerGames
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
    at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:114)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:547)
    at net.minecraft.server.Packet14BlockDig.handle(SourceFile:46)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:577)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at com.randude14.hungergames.Plugin.getSpectating(Plugin.java:448)
    at com.randude14.hungergames.listeners.BlockListener.onPlayerInteract(BlockListener.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 16 more
2012-10-10 17:30:28 [SEVERE] Could not pass event PlayerInteractEvent to HungerGames
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
    at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:114)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:547)
    at net.minecraft.server.Packet14BlockDig.handle(SourceFile:46)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:577)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at com.randude14.hungergames.Plugin.getSpectating(Plugin.java:448)
    at com.randude14.hungergames.listeners.BlockListener.onPlayerInteract(BlockListener.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 16 more
2012-10-10 17:30:28 [SEVERE] Could not pass event PlayerInteractEvent to HungerGames
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
    at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:114)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:547)
    at net.minecraft.server.Packet14BlockDig.handle(SourceFile:46)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:577)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at com.randude14.hungergames.Plugin.getSpectating(Plugin.java:448)
    at com.randude14.hungergames.listeners.BlockListener.onPlayerInteract(BlockListener.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 16 more
2012-10-10 17:30:28 [WARNING] Can't keep up! Did the system time change, or is the server overloaded?
2012-10-10 17:30:28 [SEVERE] Could not pass event PlayerInteractEvent to HungerGames
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
    at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:114)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:547)
    at net.minecraft.server.Packet14BlockDig.handle(SourceFile:46)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:577)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at com.randude14.hungergames.Plugin.getSpectating(Plugin.java:448)
    at com.randude14.hungergames.listeners.BlockListener.onPlayerInteract(BlockListener.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 16 more
2012-10-10 17:30:28 [SEVERE] Could not pass event BlockBreakEvent to HungerGames
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at net.minecraft.server.ItemInWorldManager.breakBlock(ItemInWorldManager.java:278)
    at net.minecraft.server.ItemInWorldManager.a(ItemInWorldManager.java:87)
    at net.minecraft.server.EntityPlayer.h_(EntityPlayer.java:139)
    at net.minecraft.server.World.entityJoinedWorld(World.java:1245)
    at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:511)
    at net.minecraft.server.World.playerJoinedWorld(World.java:1227)
    at net.minecraft.server.World.tickEntities(World.java:1125)
    at net.minecraft.server.WorldServer.tickEntities(WorldServer.java:428)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:563)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at com.randude14.hungergames.Plugin.getSpectating(Plugin.java:448)
    at com.randude14.hungergames.listeners.BlockListener.onBlockBreak(BlockListener.java:73)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 16 more
2012-10-10 17:30:29 [INFO] [31;1m[Announcement] Do /warp to see all warps available![m
2012-10-10 17:30:40 [SEVERE] Could not pass event PlayerInteractEvent to HungerGames
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
    at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:114)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:547)
    at net.minecraft.server.Packet14BlockDig.handle(SourceFile:46)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:577)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at com.randude14.hungergames.Plugin.getSpectating(Plugin.java:448)
    at com.randude14.hungergames.listeners.BlockListener.onPlayerInteract(BlockListener.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 16 more

**Comment by kitskub** [comment]
Just by looking at the stack trace, I know you are using an old version. Please update to the latest version.

**Comment by Mozzi3** [comment]
You are wrong.

**Comment by Mozzi3** [comment]
I have the newest version

**Comment by kitskub** [comment]
Did you delete the old version from your plugins folder?
