### ISSUE TITLE
/hg join error and an update message error.

### ISSUE THREAD

**Issue by Timpotim** [kitskub/MyHungerGames#34]
Hi,

When I type /hg join then I am teleported to a spawnpoint and my gamemode is changed to survival but it says in my chat: "An internal error occurred while attempting to perform this command", and I cannot move.
Then I look in my console and i see this error:

2012-11-18 17:03:00 [INFO] timpotim issued server command: /hg join
2012-11-18 17:03:00 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'hg' in plugin MyHungerGames v0.8.1
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:185)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:502)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:917)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:835)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:812)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:112)
    at net.minecraft.server.ServerConnection.b(SourceFile:39)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.NullPointerException
    at com.randude14.hungergames.games.HungerGame.playerEntering(HungerGame.java:823)
    at com.randude14.hungergames.games.HungerGame.join(HungerGame.java:759)
    at com.randude14.hungergames.commands.user.JoinCommand.handle(JoinCommand.java:36)
    at com.randude14.hungergames.commands.Command.execute(Command.java:62)
    at com.randude14.hungergames.commands.CommandHandler.handleUserCommand(CommandHandler.java:57)
    at com.randude14.hungergames.commands.CommandHandler.onCommand(CommandHandler.java:29)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    ... 15 more

I think this is because I have a minecraft 1.4.4 server and this plugin isn't updated to minecraft 1.4.4 or this is because I did make a mistake in the config.
My games.yml:

games:
  default:
    chests:
      chest1: -1577 59 -608 0 0 world,1.0
      chest2: -1579 59 -609 0 0 world,1.0
      chest3: -1575 59 -613 0 0 world,1.0
      chest4: -1575 59 -609 0 0 world,1.0
      chest5: -1580 59 -611 0 0 world,1.0
      chest6: -1574 59 -611 0 0 world,1.0
      chest7: -1579 59 -613 0 0 world,1.0
      chest8: -1691 67 -574 0 0 world,1.0
      chest9: -1778 57 -681 0 0 world,1.0
      chest10: -1577 59 -614 0 0 world,1.0
    blacklistedchests: {}
    fixedchests: {}
    enabled: true
    spawn: -870.774 64 -535.901 180.45 1.95 world
    spawn-points:
      spawnpoint1: -1582.5 59 -634.5 0 0 world
      spawnpoint2: -1576.5 59 -635.5 0 0 world
      spawnpoint3: -1570.5 59 -634.5 0 0 world
      spawnpoint4: -1564.5 59 -632.5 0 0 world
      spawnpoint5: -1558.5 59 -628.5 0 0 world
      spawnpoint6: -1554.5 59 -622.5 0 0 world
      spawnpoint7: -1552.5 59 -616.5 0 0 world
      spawnpoint8: -1551.5 59 -610.5 0 0 world
      spawnpoint9: -1552.5 59 -604.5 0 0 world
      spawnpoint10: -1554.5 59 -598.5 0 0 world
      spawnpoint11: -1558.5 59 -592.5 0 0 world
      spawnpoint12: -1564.5 59 -588.5 0 0 world
      spawnpoint13: -1570.5 59 -586.5 0 0 world
      spawnpoint14: -1576.5 59 -585.5 0 0 world
      spawnpoint15: -1582.5 59 -586.5 0 0 world
      spawnpoint16: -1588.5 59 -588.5 0 0 world
      spawnpoint17: -1594.5 59 -592.5 0 0 world
      spawnpoint18: -1598.5 59 -598.5 0 0 world
      spawnpoint19: -1600.5 59 -604.5 0 0 world
      spawnpoint20: -1601.5 59 -610.5 0 0 world
      spawnpoint21: -1600.5 59 -616.5 0 0 world
      spawnpoint22: -1598.5 59 -622.5 0 0 world
      spawnpoint23: -1594.5 59 -628.5 0 0 world
      spawnpoint24: -1588.5 59 -632.5 0 0 world
    itemsets:

I don't know what itemsets are. Please make a turtorial so I can setup this plugin more easily.

Another very strange error when I startup my server:
2012-11-18 16:56:27 [WARNING] [MyHungerGames] 0.8.1 - There is a new version: v0.8.1 (You are running 0.8.1)

Please repear this two bugs because this is the best hungergames plugin ever and I want to use it.........

Sorry for my bad English, I hope you understand it.

Timpotim

**Comment by kitskub** [comment]
Try the latest version available here: http://ci.chrisgward.com/view/All/job/MyHungerGames/lastBuild/

Others were having this problem and this fixes it.
