### ISSUE TITLE
Server Errors / Lags on PvP  damge

### ISSUE THREAD

**Issue by ImpactCP** [kitskub/MyHungerGames#35]
Have a big Problem with 0.9.1 >  

After i create a Arena and start the game  there is no grace time (but in config  there are 10 seconds)
If i hit another Player the following error occures:

22:50:24 [SEVERE] Could not pass event EntityDamageByEntityEvent to MyHungerGames v0.9.1
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
at org.bukkit.craftbukkit.v1_4_6.event.CraftEventFactory.callEvent(CraftEventFactory.java:81)
at org.bukkit.craftbukkit.v1_4_6.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:369)
at org.bukkit.craftbukkit.v1_4_6.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:391)
at net.minecraft.server.v1_4_6.EntityLiving.damageEntity(EntityLiving.java:686)
at net.minecraft.server.v1_4_6.EntityHuman.damageEntity(EntityHuman.java:615)
at net.minecraft.server.v1_4_6.EntityPlayer.damageEntity(EntityPlayer.java:308)
at net.minecraft.server.v1_4_6.EntityHuman.attack(EntityHuman.java:804)
at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:1115)
at net.minecraft.server.v1_4_6.Packet7UseEntity.handle(SourceFile:36)
at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)
at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:112)
at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30)
at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:598)
at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:494)
at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
at com.randude14.hungergames.Defaults$Config.getGlobalDouble(Defaults.java:163)
at com.randude14.hungergames.Defaults$Config.getDouble(Defaults.java:258)
at com.randude14.hungergames.listeners.EntityListener.onEntityDamage(EntityListener.java:34)
at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
... 21 more

This is a fresh install of the plugin only with: Multiverse, Torchcommand, Vault, Worldedit, Worldguard, PEX, HomeSpawnPlus

We build a version (from repo without the "default" sets of config in the Config.java Enum , this works fine.

seems to be problems with the cast object <> Dint?!

**Comment by kitskub** [comment]
Should be fixed in latest builds
