### ISSUE TITLE
Error spamming my console

### ISSUE THREAD

**Issue by SystemDan** [kitskub/MyHungerGames#37]
This just continuously spams my console:
[WARNING] [MyHungerGames] Task #205607 for MyHungerGames v0.9.2 generated an exception

java.lang.IllegalStateException: Not scheduled yet

```
at org.bukkit.scheduler.BukkitRunnable.getTaskId(BukkitRunnable.java:128)

at org.bukkit.scheduler.BukkitRunnable.cancel(BukkitRunnable.java:17)

at com.randude14.hungergames.commands.user.SearchCommand$2.run(SearchCommand.java:46)

at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)

at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)

at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:530)

at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:224)

at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:494)

at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:427)

at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
```

**Comment by kitskub** [comment]
Don't allows users to do /hg search. I'll actually fix the issue soon.

**Comment by kitskub** [comment]
NOTE TO SELF: Delay the cancel.
