### ISSUE TITLE
Adding new sponsor Loot Error 

### ISSUE THREAD

**Issue by NitroFox0** [kitskub/MyHungerGames#45]
when ever i try adding a new sponsor loot it gives me an error even when i type in the item

**Comment by kitskub** [comment]
What error?

**Comment by NitroFox0** [comment]
org.bukkit.command.CommandException: Unhandled exception executing command 'hga'
 in plugin MyHungerGames v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:18
9)
        at org.bukkit.craftbukkit.v1_5_R2.CraftServer.dispatchCommand(CraftServe
r.java:523)
        at net.minecraft.server.v1_5_R2.PlayerConnection.handleCommand(PlayerCon
nection.java:966)
        at net.minecraft.server.v1_5_R2.PlayerConnection.chat(PlayerConnection.j
ava:884)
        at net.minecraft.server.v1_5_R2.PlayerConnection.a(PlayerConnection.java
:841)
        at net.minecraft.server.v1_5_R2.Packet3Chat.handle(Packet3Chat.java:44)
        at net.minecraft.server.v1_5_R2.NetworkManager.b(NetworkManager.java:292
)
        at net.minecraft.server.v1_5_R2.PlayerConnection.d(PlayerConnection.java
:110)
        at net.minecraft.server.v1_5_R2.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.v1_5_R2.DedicatedServerConnection.b(SourceFile:3
0)
        at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:5
80)
        at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:2
25)
        at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:4
76)
        at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java
:409)
        at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:5
73)
Caused by: java.lang.NullPointerException
        at me.kitskub.hungergames.commands.admin.add.AddSponsorLootCommand.handl
ePlayer(AddSponsorLootCommand.java:32)
        at me.kitskub.hungergames.commands.PlayerCommand.handle(PlayerCommand.ja
va:28)
        at me.kitskub.hungergames.commands.Command.execute(Command.java:68)
        at me.kitskub.hungergames.commands.Command.execute(Command.java:65)
        at me.kitskub.hungergames.commands.CommandHandler.handleCommand(CommandH
andler.java:40)
        at me.kitskub.hungergames.commands.CommandHandler.onCommand(CommandHandl
er.java:22)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        ... 15 more

**Comment by guy0090** [comment]
Im getting the same error haha, any idea on why this happens?
