### ISSUE TITLE
error in console?

### ISSUE THREAD

**Issue by arjove** [kitskub/MyHungerGames#50]
2013-05-07 20:20:58 [WARNING] [MyHungerGames] Task #39 for MyHungerGames v1.0 generated an exception
java.lang.NullPointerException
 at me.kitskub.hungergames.listeners.ActivityListener.run(ActivityListener.java:53)
 at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:58)
 at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
 at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:509)
 at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:224)
 at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:472)
 at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:404)
 at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

i dont know why but it crashed the server.

**Comment by NitroFox0** [comment]
Try the new version of the plugin here is the download http://empirehostings.com:8080/job/MyHungerGames/39/
