### ISSUE TITLE
Sponsor Loot Error

### ISSUE THREAD

**Issue by guy0090** [kitskub/MyHungerGames#57]
I've been doing the /hga add sponsorloot <price> and I always seem to get this printed to the console:
12:13:44 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'hga' in plugin MyHungerGames v1.1
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:523)
    at net.minecraft.server.v1_5_R3.PlayerConnection.handleCommand(PlayerConnection.java:965)
    at net.minecraft.server.v1_5_R3.PlayerConnection.chat(PlayerConnection.java:883)
    at net.minecraft.server.v1_5_R3.PlayerConnection.a(PlayerConnection.java:840)
    at com.bergerkiller.bukkit.common.internal.network.CommonPacketHandler$CommonPlayerConnection.a(CommonPacketHandler.java:531)
    at net.minecraft.server.v1_5_R3.Packet3Chat.handle(Packet3Chat.java:44)
    at net.minecraft.server.v1_5_R3.NetworkManager.b(NetworkManager.java:292)
    at net.minecraft.server.v1_5_R3.PlayerConnection.d(PlayerConnection.java:109)
    at net.minecraft.server.v1_5_R3.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:581)
    at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
    at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
    at me.kitskub.hungergames.commands.admin.add.AddSponsorLootCommand.handlePlayer(AddSponsorLootCommand.java:32)
    at me.kitskub.hungergames.commands.PlayerCommand.handle(PlayerCommand.java:28)
    at me.kitskub.hungergames.commands.Command.execute(Command.java:68)
    at me.kitskub.hungergames.commands.Command.execute(Command.java:65)
    at me.kitskub.hungergames.commands.CommandHandler.handleCommand(CommandHandler.java:40)
    at me.kitskub.hungergames.commands.CommandHandler.onCommand(CommandHandler.java:22)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    ... 16 more

Any fixes for it? 
Other then that, the best HG plugin I've seen so far! :D

**Comment by ghost** [comment]
Any news on this yet?
