### ISSUE TITLE
Error - should-clear-inv

### ISSUE THREAD

**Issue by rossedlin** [kitskub/MyHungerGames#7]
On setting "should-clear-inv"  to "true" it produces an error when using the "hg join" command.

CraftBukkit: 1.2.5 R3.0
Using version: v0.3.1

org.bukkit.command.CommandException: Unhandled exception executing command 'hg'
in plugin HungerGames v0.3.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:16
6)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:4
79)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.
java:821)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:781)

```
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
    at net.minecraft.serverhook.NetServerHandlerProxy.a(NetServerHandlerProx
```

y.java:141)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
        at net.minecraft.serverhook.NetServerHandlerProxy.a(NetServerHandlerProx
y.java:83)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:7
8)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:567)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:459)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NullPointerException
        at com.randude14.hungergames.Plugin.parseToString(Plugin.java:451)
        at com.randude14.hungergames.games.HungerGame.saveTo(HungerGame.java:117
)
        at com.randude14.hungergames.GameManager.saveGame(GameManager.java:191)
        at com.randude14.hungergames.commands.CommandHandler.handleUserCommand(C
ommandHandler.java:214)
        at com.randude14.hungergames.commands.CommandHandler.onCommand(CommandHa
ndler.java:32)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        ... 14 more

**Comment by kitskub** [comment]
Fixed?
